/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entite.InfosDiverse;
import entite.MessageDivers;
import entite.Note;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author daniel
 */
public class JD_Admin extends javax.swing.JDialog {
   private List<InfosDiverse> listinfos;
   private List<Note> listNote;
   private List<MessageDivers> listMessage;
   private accesData.AccesData ad;
   
    /**
     * Creates new form JD_Admin
     */
    public JD_Admin(java.awt.Frame parent, boolean modal, accesData.AccesData ad) {
        super(parent, modal);
        this.ad=ad;
        listinfos=ad.getListe("InfosDiverse.findAll");
        listMessage=ad.getListe("MessageDivers.findAll");
        listNote=ad.getListe("Note.findAll");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        JBAjouter = new javax.swing.JButton();
        JBModifier = new javax.swing.JButton();
        JBSupprimer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        JTFRespo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTFContact = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableNote = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        JTFLibelle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JCPoint = new javax.swing.JComboBox();
        JBAjouterNote = new javax.swing.JButton();
        JBModifierNote = new javax.swing.JButton();
        JBSupprimerNote = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administration");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Responsable", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        new utilites.table.GestionTable().chargeTable(jTable1, new entite.InfosDiverse().dataTable(listinfos),new String[] { "Responsable", "Contact"},new Class[] {java.lang.String.class, java.lang.String.class});

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        JBAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouter.png"))); // NOI18N
        JBAjouter.setText("Ajouter");
        JBAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterActionPerformed(evt);
            }
        });

        JBModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modifier.gif"))); // NOI18N
        JBModifier.setText("Modifier");
        JBModifier.setEnabled(false);
        JBModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModifierActionPerformed(evt);
            }
        });

        JBSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer.png"))); // NOI18N
        JBSupprimer.setText("Supprimer");
        JBSupprimer.setEnabled(false);
        JBSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSupprimerActionPerformed(evt);
            }
        });

        jLabel2.setText("Le message ci-bas est celui qui est affiché en bas de page des plannings");

        jScrollPane2.setViewportView(jEditorPane1);
        jEditorPane1.setText(listMessage.get(0).getSms());

        jLabel1.setText("Responsable");

        JTFRespo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFRespoActionPerformed(evt);
            }
        });

        jLabel3.setText("Contact");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFRespo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFContact, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBSupprimer))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFRespo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JBAjouter)
                        .addGap(18, 18, 18)
                        .addComponent(JBModifier)
                        .addGap(18, 18, 18)
                        .addComponent(JBSupprimer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Infos divers", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTableNote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Libelle", "Point"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNoteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableNote);
        new utilites.table.GestionTable().chargeTable(jTableNote, new Note().dataTable(listNote),new String[] { "Libelle", "Point"},new Class[] {java.lang.String.class, java.lang.Integer.class});

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jLabel4.setText("Libelle");

        JTFLibelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFLibelleActionPerformed(evt);
            }
        });

        jLabel5.setText("Point");

        JCPoint.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  ", "-2", "-1", "0", "1", "2", "3", "4", "5" }));

        JBAjouterNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouter.png"))); // NOI18N
        JBAjouterNote.setText("Ajouter");
        JBAjouterNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterNoteActionPerformed(evt);
            }
        });

        JBModifierNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modifier.gif"))); // NOI18N
        JBModifierNote.setText("Modifier");
        JBModifierNote.setEnabled(false);
        JBModifierNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModifierNoteActionPerformed(evt);
            }
        });

        JBSupprimerNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer.png"))); // NOI18N
        JBSupprimerNote.setText("Supprimer");
        JBSupprimerNote.setEnabled(false);
        JBSupprimerNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSupprimerNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(JBAjouterNote, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBModifierNote, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBSupprimerNote))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(JCPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAjouterNote)
                    .addComponent(JBModifierNote)
                    .addComponent(JBSupprimerNote))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Note", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterActionPerformed
        // TODO add your handling code here:
        InfosDiverse fd=new InfosDiverse();
        fd.setResponsable(JTFRespo.getText().trim());
        fd.setTel(JTFContact.getText().trim());
        
        ad.getTransac().begin();
        ad.getEm().persist(fd);
        ad.getTransac().commit();
        
        if(jEditorPane1.getText()!=null && listMessage.get(0).getSms().equalsIgnoreCase(null)){
            MessageDivers md=new MessageDivers();
            md.setSms(jEditorPane1.getText().trim());
            ad.getTransac().begin();
            ad.getEm().persist(md);
            ad.getTransac().commit();
        }
        
       
        listinfos=ad.getListe("InfosDiverse.findAll");
        listMessage=ad.getListe("MessageDivers.findAll");
        
        new utilites.table.GestionTable().chargeTable(jTable1, new entite.InfosDiverse().dataTable(listinfos),new String[] { "Responsable", "Contact"},new Class[] {java.lang.String.class, java.lang.String.class});
        jEditorPane1.setText(listMessage.get(0).getSms());
    }//GEN-LAST:event_JBAjouterActionPerformed

    private void JBModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModifierActionPerformed
        // TODO add your handling code here:
       
        InfosDiverse fd=ad.getEm().find(InfosDiverse.class,listinfos.get(jTable1.getSelectedRow()).getIdInfos());
        
        fd.setResponsable(JTFRespo.getText().trim());
        fd.setTel(JTFContact.getText().trim());
        
        ad.getTransac().begin();
        ad.getEm().flush();
        ad.getTransac().commit();
        
        if(!jEditorPane1.getText().equalsIgnoreCase(listMessage.get(0).getSms())){
            MessageDivers md=ad.getEm().find(MessageDivers.class,listMessage.get(0).getIdMessage());
           
            md.setSms(jEditorPane1.getText().trim());
            ad.getTransac().begin();
            ad.getEm().flush();
            ad.getTransac().commit();
        }
        
        listinfos=ad.getListe("InfosDiverse.findAll");
        listMessage=ad.getListe("MessageDivers.findAll");
        
        new utilites.table.GestionTable().chargeTable(jTable1, new entite.InfosDiverse().dataTable(listinfos),new String[] { "Responsable", "Contact"},new Class[] {java.lang.String.class, java.lang.String.class});
        jEditorPane1.setText(listMessage.get(0).getSms());
        JBModifier.setEnabled(false);
        JBSupprimer.setEnabled(false);
    }//GEN-LAST:event_JBModifierActionPerformed

    private void JBSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSupprimerActionPerformed
        // TODO add your handling code here:
        InfosDiverse fd=ad.getEm().find(InfosDiverse.class,listinfos.get(jTable1.getSelectedRow()).getIdInfos());
        if(JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment supprimer ce responsable?","Confirmation",JOptionPane.OK_CANCEL_OPTION)!=0){
           return ;
        }
        ad.getTransac().begin();
        ad.getEm().remove(fd);
        ad.getTransac().commit();
        
        listinfos=ad.getListe("InfosDiverse.findAll");
        listMessage=ad.getListe("MessageDivers.findAll");
        
        new utilites.table.GestionTable().chargeTable(jTable1, new entite.InfosDiverse().dataTable(listinfos),new String[] { "Responsable", "Contact"},new Class[] {java.lang.String.class, java.lang.String.class});

        JBModifier.setEnabled(false);
        JBSupprimer.setEnabled(false);
        
    }//GEN-LAST:event_JBSupprimerActionPerformed

    private void JTFRespoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFRespoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFRespoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        new utilites.table.GestionTable().actionClicTable(jTable1, new JTextField[]{JTFRespo,JTFContact},new int[]{1,1});
        JBModifier.setEnabled(true);
        JBSupprimer.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void JBAjouterNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterNoteActionPerformed
        // TODO add your handling code here:
        Note n=new Note();
        n.setLibelle(JTFLibelle.getText().trim());
        n.setPoint(Integer.parseInt(JCPoint.getSelectedItem().toString()));
        
        ad.getTransac().begin();
        ad.getEm().remove(n);
        ad.getTransac().commit();
        
        listNote=ad.getListe("Note.findAll");
        
        new utilites.table.GestionTable().chargeTable(jTableNote, new Note().dataTable(listNote),new String[] { "Libelle", "Point"},new Class[] {java.lang.String.class, java.lang.Integer.class});

        
    }//GEN-LAST:event_JBAjouterNoteActionPerformed

    private void JBModifierNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModifierNoteActionPerformed
        // TODO add your handling code here:
        Note n=ad.getEm().find(Note.class,listNote.get(jTableNote.getSelectedRow()));
        n.setLibelle(JTFLibelle.getText().trim());
        n.setPoint(Integer.parseInt(JCPoint.getSelectedItem().toString()));
        
        ad.getTransac().begin();
        ad.getEm().flush();
        ad.getTransac().commit();
        
        listNote=ad.getListe("Note.findAll");
        
        new utilites.table.GestionTable().chargeTable(jTableNote, new Note().dataTable(listNote),new String[] { "Libelle", "Point"},new Class[] {java.lang.String.class, java.lang.Integer.class});

    }//GEN-LAST:event_JBModifierNoteActionPerformed

    private void JBSupprimerNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSupprimerNoteActionPerformed
        // TODO add your handling code here:
        Note n=ad.getEm().find(Note.class,listNote.get(jTableNote.getSelectedRow()));
       
        if(JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment supprimer cette note?","Confirmation",JOptionPane.OK_CANCEL_OPTION)!=0){
           return ;
        }
         
        ad.getTransac().begin();
        ad.getEm().remove(n);
        ad.getTransac().commit();
        
        listNote=ad.getListe("Note.findAll");
        
        new utilites.table.GestionTable().chargeTable(jTableNote, new Note().dataTable(listNote),new String[] { "Libelle", "Point"},new Class[] {java.lang.String.class, java.lang.Integer.class});

    }//GEN-LAST:event_JBSupprimerNoteActionPerformed

    private void JTFLibelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFLibelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFLibelleActionPerformed

    private void jTableNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNoteMouseClicked
        // TODO add your handling code here:
        new utilites.table.GestionTable().actionClicTable(jTableNote, new JTextField[]{JTFLibelle}, new int[]{1});
        JCPoint.setSelectedItem(jTableNote.getValueAt(jTableNote.getSelectedRow(), 1));
        JBModifierNote.setEnabled(true);
        JBSupprimerNote.setEnabled(true);
    }//GEN-LAST:event_jTableNoteMouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAjouter;
    private javax.swing.JButton JBAjouterNote;
    private javax.swing.JButton JBModifier;
    private javax.swing.JButton JBModifierNote;
    private javax.swing.JButton JBSupprimer;
    private javax.swing.JButton JBSupprimerNote;
    private javax.swing.JComboBox JCPoint;
    private javax.swing.JTextField JTFContact;
    private javax.swing.JTextField JTFLibelle;
    private javax.swing.JTextField JTFRespo;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableNote;
    // End of variables declaration//GEN-END:variables
}
