/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.InputStream;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author daniel
 */
public class JD_Imp extends javax.swing.JDialog {
    private String rapport;
    private HashMap map;

    /**
     * Creates new form JD_Imp
     */
    public JD_Imp(java.awt.Frame parent, boolean modal,String rapport,HashMap map) {
        super(parent, modal);
        this.rapport=rapport;
        this.map=map;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        InputStream reportStream = this.getClass().getResourceAsStream(rapport);

        // Convert template to JasperDesign
        try{
            JasperDesign jd = JRXmlLoader.load(reportStream);

            // Compile design to JasperReport
            JasperReport jr = JasperCompileManager.compileReport(jd);

            // Create the JasperPrint object
            // Make sure to pass the JasperReport, report parameters, and data source
            JasperPrint jp = JasperFillManager.fillReport(jr,map, new utilites.MaConnexion().getInstance());
            // JasperViewer jv = new JasperViewer(jp);
            JRViewer jrv=new JRViewer(jp);

            jScrollPane1.setViewportView(jrv);
            jScrollPane1.repaint();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, ""+e.getMessage());
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
