/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entite.Site;
import entite.THoraire;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class JD_TH extends javax.swing.JDialog {
     private accesData.AccesData ad;
     private List<THoraire> listTH;
    /**
     * Creates new form JD_TH
     */
    public JD_TH(java.awt.Frame parent, boolean modal,accesData.AccesData ad) {
        super(parent, modal);
        this.ad=ad;
        listTH=ad.getListe("THoraire.findAll");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableTHoraire = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBoxHD = new javax.swing.JComboBox(THoraire.TabHeure);
        JBAjouterTHSite = new javax.swing.JButton();
        JBSupprimerTHSite = new javax.swing.JButton();
        jComboBoxHF = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tranches horaires");
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des tranches horaires existantes"));

        jTableTHoraire.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Heure du début", "Heure de la fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTHoraire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTHoraireMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableTHoraire);
        new utilites.table.GestionTable().chargeTable(jTableTHoraire, new THoraire().dataTable(listTH),new String[] {"Heure du début", "Heure de la fin"},new Class[] {java.lang.String.class, java.lang.String.class});

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel11);

        jLabel21.setText("Heure du début");

        jLabel22.setText("Heure de la fin");

        jComboBoxHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHDActionPerformed(evt);
            }
        });

        JBAjouterTHSite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouter.png"))); // NOI18N
        JBAjouterTHSite.setText("Ajouter");
        JBAjouterTHSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterTHSiteActionPerformed(evt);
            }
        });

        JBSupprimerTHSite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer.png"))); // NOI18N
        JBSupprimerTHSite.setText("Supprimer");
        JBSupprimerTHSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSupprimerTHSiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JBAjouterTHSite, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBSupprimerTHSite)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxHD, 0, 136, Short.MAX_VALUE)
                            .addComponent(jComboBoxHF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(197, 197, 197))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBoxHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBoxHF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAjouterTHSite)
                    .addComponent(JBSupprimerTHSite))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableTHoraireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTHoraireMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("k:mm");
        THoraire th=listTH.get(jTableTHoraire.getSelectedRow());
        jComboBoxHD.setSelectedItem(formater.format(th.getHeureDebut()));
        
    }//GEN-LAST:event_jTableTHoraireMouseClicked

    private void jComboBoxHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHDActionPerformed
        // TODO add your handling code here:
        new utilites.Utilitaire().chargeCombo(jComboBoxHF, new THoraire().getHeureFins(jComboBoxHD.getSelectedItem().toString()));
        
        
    }//GEN-LAST:event_jComboBoxHDActionPerformed

    private void JBAjouterTHSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterTHSiteActionPerformed
        // TODO add your handling code here:
      
        ad.requeteNative("insert into t_horaire(heure_debut,heure_fin) values('"+jComboBoxHD.getSelectedItem().toString()+"' , '"+jComboBoxHF.getSelectedItem().toString()+"' )");

        listTH=ad.getListe("THoraire.findAll");      

        new utilites.table.GestionTable().chargeTable(jTableTHoraire, new THoraire().dataTable(listTH),new String[] {"Heure du début", "Heure de la fin"},new Class[] {java.lang.String.class, java.lang.String.class});

    }//GEN-LAST:event_JBAjouterTHSiteActionPerformed

    private void JBSupprimerTHSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSupprimerTHSiteActionPerformed
        // TODO add your handling code here:
        if(jTableTHoraire.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Vous devez d'abord s\u00E9lectionner une ligne dans la liste des tranches horaires");
            return;
        }
        if(JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment supprimer cette valeur?")!=0){
            return ;
        }
        THoraire th=ad.getEm().find(THoraire.class,listTH.get(jTableTHoraire.getSelectedRow()).getIdtHoraire());

        //On valide les modifications dans la BD
        ad.getTransac().begin();
        ad.getEm().remove(th);
        ad.getTransac().commit();
        
        listTH=ad.getListe("THoraire.findAll");      

        new utilites.table.GestionTable().chargeTable(jTableTHoraire, new THoraire().dataTable(listTH),new String[] {"Heure du début", "Heure de la fin"},new Class[] {java.lang.String.class, java.lang.String.class});

    }//GEN-LAST:event_JBSupprimerTHSiteActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAjouterTHSite;
    private javax.swing.JButton JBSupprimerTHSite;
    private javax.swing.JComboBox jComboBoxHD;
    private javax.swing.JComboBox jComboBoxHF;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableTHoraire;
    // End of variables declaration//GEN-END:variables
}
