/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import metier.Etat;
import metier.Repartion;

import entite.*;
import utilites.Utilitaire;
import utilites.table.GestionTable;

/**
 *
 * @author daniel
 */
public class JP_Repartition_Manuelle extends javax.swing.JPanel {

    /**
     * Creates new form JP_Repartition_Manuelle
     */
    private int ligne;//ligne qui est selectionne dans la table plannings, utile pour les modifications
    private Etat etat;
    private entite.Proclamateur proclamateurPlanning;
    private Vector donneetable;
    private String dateDeb,dateFin;
    private Repartion repartion;
    private Vector<Proclamateur> vecProPlanning;
    private entite.Site site;
    public JP_Repartition_Manuelle(Repartion r,String DateDeb,String dateFin,Vector<Proclamateur> vecProPlanning,Site s) {
        this.repartion=r;
        this.dateDeb=dateDeb;
        this.dateFin=dateFin;
        this.vecProPlanning=vecProPlanning;
        this.site=s;
        this.etat=new Etat();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProclamateurElligible = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePlanningManuel = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jButtonSauvegarder = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTFNomProclamateur = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTFCongrégation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JComboJour = new javax.swing.JComboBox(repartion.getDateRepartion());
        jLabel4 = new javax.swing.JLabel();
        JBAjouter = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePlanningProclamateurElligible = new javax.swing.JTable();
        JLabelJour = new javax.swing.JLabel();
        jComboHeureDebPlanning = new javax.swing.JComboBox();
        jButtonModifierPlanning = new javax.swing.JButton();
        jButtonSupprimerPlanning = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Proclamateurs élligibles"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tableProclamateurElligible.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom du proclamateur", "Congrégation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProclamateurElligible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProclamateurElligibleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProclamateurElligible);
        //on prepare les donnees pour affichage dans les tables
        //new utilites.table.GestionTable().chargeTable(tableProclamateurElligible, new Proclamateur().listeproclamateurForPlanningManuel(site),new String[] {  "Nom du proclamateur", "Congrégation"},new Class[] {java.lang.String.class, java.lang.String.class});

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Planning "));
        jPanel4.setLayout(new java.awt.BorderLayout());

        tablePlanningManuel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom du proclamateur", "Congrégation", "Jour", "Heure du début", "Heure de la fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePlanningManuel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePlanningManuelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePlanningManuel);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jButtonSauvegarder.setText("Sauvegarder");
        jButtonSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSauvegarderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButtonSauvegarder)
                .addGap(0, 357, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSauvegarder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Proclamateur sélectionné"));

        jLabel1.setText("Nom");

        JTFNomProclamateur.setEditable(false);

        jLabel2.setText("Congrégation");

        JTFCongrégation.setEditable(false);

        jLabel3.setText("Jour");

        JComboJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboJourActionPerformed(evt);
            }
        });

        jLabel4.setText("Heure du début");

        JBAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouter.png"))); // NOI18N
        JBAjouter.setText("Ajouter");
        JBAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Emploi de temps du proclamateur"));

        tablePlanningProclamateurElligible.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jour", "Heure du début", "Heure de la fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablePlanningProclamateurElligible);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(274, Short.MAX_VALUE)))
        );

        jButtonModifierPlanning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modifier.gif"))); // NOI18N
        jButtonModifierPlanning.setText("Modifier");
        jButtonModifierPlanning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierPlanningActionPerformed(evt);
            }
        });

        jButtonSupprimerPlanning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer.png"))); // NOI18N
        jButtonSupprimerPlanning.setText("Supprimer");
        jButtonSupprimerPlanning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerPlanningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(JBAjouter)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFCongrégation, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFNomProclamateur, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonModifierPlanning)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonSupprimerPlanning))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jComboHeureDebPlanning, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JComboJour, javax.swing.GroupLayout.Alignment.LEADING, 0, 137, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(JLabelJour, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFNomProclamateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFCongrégation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(JComboJour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JLabelJour, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboHeureDebPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAjouter)
                    .addComponent(jButtonModifierPlanning)
                    .addComponent(jButtonSupprimerPlanning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSupprimerPlanningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerPlanningActionPerformed
        // TODO add your handling code here:
        
        if(JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment supprimer ce proclamateur du planning?","Confirmation",JOptionPane.OK_CANCEL_OPTION)==0){
          etat.deleteEtat(tablePlanningManuel.getSelectedRow());
          new utilites.table.GestionTable().chargeTable(tablePlanningManuel, etat.getVecListeEtat(),new String[] {"Nom du proclamateur", "Congrégation", "Jour", "Heure du début", "Heure de la fin"},new Class[] {java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class});
    
        }
        
    }//GEN-LAST:event_jButtonSupprimerPlanningActionPerformed

    private void tableProclamateurElligibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProclamateurElligibleMouseClicked
        // TODO add your handling code here:
        proclamateurPlanning =vecProPlanning.elementAt(tableProclamateurElligible.getSelectedRow());
        new GestionTable().actionClicTable(tableProclamateurElligible, new JTextField[]{JTFNomProclamateur,JTFCongrégation},new int[]{1,1});
        JLabelJour.setText(repartion.getJourRepartionFromPosition(0));
        new utilites.table.GestionTable().chargeTable(tablePlanningProclamateurElligible, new Proclamateur().dataTableET(proclamateurPlanning.getEmploiTCollection()),new String[] {"Jour", "Heure du début", "Heure de la fin"},new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
	
    }//GEN-LAST:event_tableProclamateurElligibleMouseClicked

    private void JComboJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboJourActionPerformed
        // TODO add your handling code here:
        JLabelJour.setText(repartion.getJourRepartionFromPosition(JComboJour.getSelectedIndex()));
        
    }//GEN-LAST:event_JComboJourActionPerformed

    private void JBAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterActionPerformed
//        // TODO add your handling code here:
//        etat=new Etat(proclamateurPlanning,JComboJour.getSelectedItem().toString(),JLabelJour.getText(),jComboHeureDebPlanning.getSelectedItem().toString());
//        etat.setSITE(site);
//        if(!etat.addEtat(etat)){
//            JOptionPane.showMessageDialog(this,"Ce proclamateur est d\u00E9ja occup\u00E9 pour ce jour");
//            return;
//        }else{
//            new utilites.table.GestionTable().chargeTable(tablePlanningManuel, etat.getVecListeEtat(),new String[] {"Nom du proclamateur", "Congrégation", "Jour", "Heure du début", "Heure de la fin"},new Class[] {java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class});
//   }
//        
    }//GEN-LAST:event_JBAjouterActionPerformed

    private void jButtonModifierPlanningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierPlanningActionPerformed
        // TODO add your handling code here:
//        etat.updateEtat(ligne,JTFNomProclamateur.getText(),JTFCongrégation.getText(),JLabelJour.getText(),JComboJour.getSelectedItem().toString(),jComboHeureDebPlanning.getSelectedItem().toString());
        new utilites.table.GestionTable().chargeTable(tablePlanningManuel, etat.getVecListeEtat(),new String[] {"Nom du proclamateur", "Congrégation", "Jour", "Heure du début", "Heure de la fin"},new Class[] {java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class});
 
    }//GEN-LAST:event_jButtonModifierPlanningActionPerformed

    private void tablePlanningManuelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePlanningManuelMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            ligne=tablePlanningManuel.getSelectedRow();
            JTFNomProclamateur.setText(tablePlanningManuel.getValueAt(ligne,0).toString());
            JTFCongrégation.setText(tablePlanningManuel.getValueAt(ligne,1).toString());
            StringTokenizer st=new StringTokenizer(tablePlanningManuel.getValueAt(ligne,2).toString(),", ");
            String jour=st.nextToken();
            String date=st.nextToken();
            JLabelJour.setText(jour);
            JComboJour.setSelectedItem(date);
            jComboHeureDebPlanning.setSelectedItem(tablePlanningManuel.getValueAt(ligne,3).toString());
            System.out.println("heure debut selectionne:"+tablePlanningManuel.getValueAt(ligne,3).toString());
        }
    }//GEN-LAST:event_tablePlanningManuelMouseClicked

    private void jButtonSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSauvegarderActionPerformed
        // TODO add your handling code here:
        etat.sauvegarderPlanning();
        //JFileChooser jfc=new JFileChooser("../");
        //jfc.setVisible(true);
       // if(jfc==)
//        new Etat().doExcelFile(etat.getVecEtat(),"D://monetat");
        System.out.println("taille vec:"+etat.getVecEtat().size());
    }//GEN-LAST:event_jButtonSauvegarderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAjouter;
    private javax.swing.JComboBox JComboJour;
    private javax.swing.JLabel JLabelJour;
    private javax.swing.JTextField JTFCongrégation;
    private javax.swing.JTextField JTFNomProclamateur;
    private javax.swing.JButton jButtonModifierPlanning;
    private javax.swing.JButton jButtonSauvegarder;
    private javax.swing.JButton jButtonSupprimerPlanning;
    private javax.swing.JComboBox jComboHeureDebPlanning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablePlanningManuel;
    private javax.swing.JTable tablePlanningProclamateurElligible;
    private javax.swing.JTable tableProclamateurElligible;
    // End of variables declaration//GEN-END:variables
}
