/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entite.Jour;
import entite.Planning;
import entite.Proclamateur;
import entite.Site;
import java.awt.BorderLayout;
import java.io.File;
import java.io.InputStream;
import java.util.Vector;
import javax.swing.JFileChooser;
import metier.Etat;
import metier.Repartion;
import java.util.*;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
import utilites.Lis_Utilites;
import utilites.presentation.RenduTable_Doublon_De_Valeur;
/**
 *
 * @author daniel
 */
public class JP_Repartition_Auto extends javax.swing.JPanel {
    private Vector donneetable;
    private Vector<Vector> procRechange;
    private String dateDeb,dateFin;
    private Repartion repartion;
    private Site s;
    private accesData.AccesData ad;
    private List<Planning> listPlanning;
    public static int IDCHOIX=-10;
    private int maxGroupe;
            
    /**
     * Creates new form JP_Repartition_Auto
     */
    public JP_Repartition_Auto(Repartion r,String DateDeb,String DateFin,accesData.AccesData ad,Site s) {
        this.repartion=r;
        this.dateDeb=DateDeb;
        this.dateFin=DateFin;
        this.s=s;
        this.ad=ad;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JLabelDateDeb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLabelDateFin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRepartionAuto = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        JBExcel = new javax.swing.JButton();
        JBSupprimer = new javax.swing.JButton();
        JBPdf = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Planning de répartition du");

        JLabelDateDeb.setText(dateDeb);
        JLabelDateDeb.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        JLabelDateDeb.setForeground(new java.awt.Color(153, 0, 51));

        jLabel2.setText("Au");

        JLabelDateFin.setText(dateFin);
        JLabelDateFin.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        JLabelDateFin.setForeground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelDateDeb, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(JLabelDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(JLabelDateDeb, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        tableRepartionAuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom proclamateur", "Congrégation", "Jour", "Heure du début", "Heure de la fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRepartionAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRepartionAutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRepartionAuto);
        maxGroupe=Integer.parseInt(ad.requeteNativeQuery("select max(groupe) from planning").toString());
        listPlanning=ad.getListe("Planning.findByGroupe", "groupe", maxGroupe);

        //on prepare les donnees pour affichage dans les tables

        new utilites.table.GestionTable().chargeTable(tableRepartionAuto, new entite.Planning().dataTablePlanning(listPlanning),new String[] { "Nom proclamateur", "Congrégation", "Jour", "Heure du début", "Heure de la fin"},new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class});
        JBExcel.setEnabled(true);
        JBPdf.setEnabled(true);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        JBExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/excel.gif"))); // NOI18N
        JBExcel.setText("Générer Excel");
        JBExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBExcelActionPerformed(evt);
            }
        });

        JBSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer.png"))); // NOI18N
        JBSupprimer.setText("Supprimer");
        JBSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSupprimerActionPerformed(evt);
            }
        });

        JBPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pdf.gif"))); // NOI18N
        JBPdf.setText("Générer PDF");
        JBPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(JBExcel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBSupprimer)
                .addGap(0, 117, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBExcel)
                    .addComponent(JBPdf)
                    .addComponent(JBSupprimer))
                .addGap(31, 31, 31))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void JBExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBExcelActionPerformed
        // TODO add your handling code here:
        //etat.sauvegarderPlanning();
        JFileChooser fc = new JFileChooser();
	repartion.setPlanningAuto(listPlanning);	
        int retour = fc.showOpenDialog(this);
	if ( retour == JFileChooser.APPROVE_OPTION )
	{   
             //Vecteur de Jour
             Vector<Jour> vecJour=new Jour().getAllDays(ad.getListe("Jour.findAll"));
         
             Vector vd=s.getHeureDeb(s);
             Vector vf=s.getHeureFin(s);
	     File f= fc.getSelectedFile();
             new Etat().makeExcelFile(repartion.getVecPlanning(),vd,vf,f.getAbsolutePath(),s,vecJour);
             System.out.println("taille vec:"+repartion.getEtat());
		             
	}
        
    }//GEN-LAST:event_JBExcelActionPerformed

    private void tableRepartionAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRepartionAutoMouseClicked
        // TODO add your handling code here:
        int rowS=tableRepartionAuto.getSelectedRow();
        String jour=tableRepartionAuto.getValueAt(rowS, 2).toString();
        jour=jour.substring(0, jour.indexOf(","));
//        System.out.println("jour "+jour);
        String leProclamateurSelectionner=tableRepartionAuto.getValueAt(rowS, 0).toString();
        if(evt.getClickCount()==2){
            procRechange=new entite.Planning().getProclamateurForChange(tableRepartionAuto.getValueAt(rowS, 3).toString(), tableRepartionAuto.getValueAt(rowS, 4).toString(),jour , s.getIdsite());
            Vector vi=new entite.Planning().getProclamateurForChange(tableRepartionAuto.getValueAt(rowS, 3).toString(), tableRepartionAuto.getValueAt(rowS, 4).toString(),jour , s.getIdsite());
           
//            System.out.println("selection "+procRechange);
            JD_Proc_Dispo jdpd=new JD_Proc_Dispo(null, true,vi);
            jdpd.setVisible(true);
            //on recherche le proclamateur qui a ete selectionne
            if(IDCHOIX!=-10){
                
                Proclamateur p=ad.getEm().find(Proclamateur.class, Integer.parseInt(procRechange.elementAt(IDCHOIX).firstElement().toString()));
                //on obtient la ligne du planning qui a ete selectionne
                Planning pl=(Planning)listPlanning.get(rowS);
                //modification dans la BDD
                pl=ad.getEm().find(Planning.class,pl.getIdplanning());
                pl.setIdproclamateur(p);
                ad.getTransac().begin();
                ad.getEm().flush();
                ad.getTransac().commit();
                //modification sur la table
                System.out.println("proclamateur "+p.getNom());
                tableRepartionAuto.setValueAt(p.getNom(), rowS, 0);
                tableRepartionAuto.getModel().setValueAt(p.getNom(), rowS, 0);
//                tableRepartionAuto.getModel().
                //modification dans l'etat
            }
            
            
            
        }else{//mise en evidence des doublons
            RenduTable_Doublon_De_Valeur rd=new RenduTable_Doublon_De_Valeur(leProclamateurSelectionner);
            tableRepartionAuto.setDefaultRenderer(String.class, rd);
            tableRepartionAuto.repaint();
        }
    }//GEN-LAST:event_tableRepartionAutoMouseClicked

    private void JBSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSupprimerActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment supprimer ce planning?", "Confirmation",JOptionPane.OK_CANCEL_OPTION)!=0){
             return ;
        }
        new Planning().deletePlanning(maxGroupe);
        JBExcel.setEnabled(false);
    }//GEN-LAST:event_JBSupprimerActionPerformed

    private void JBPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPdfActionPerformed
        // TODO add your handling code here:
                        new Planning().doPlanningPdf(maxGroupe, s.getLieu());
                        InputStream reportStream = this.getClass().getResourceAsStream("/propriete/Planning.jrxml"); 
                        HashMap map=new HashMap();
                         Lis_Utilites lu=new Lis_Utilites("propriete/chemin.properties");
                         String chemin=lu.getValeurProperties("chemin").toString();
                         map.put("SUBREPORT_DIR",chemin);
                        
                        // Convert template to JasperDesign  
                        try{
                             JasperDesign jd = JRXmlLoader.load(reportStream);  
                  
                             // Compile design to JasperReport  
                             JasperReport jr = JasperCompileManager.compileReport(jd); 
                          
                            // Create the JasperPrint object  
                            // Make sure to pass the JasperReport, report parameters, and data source  
                            JasperPrint jp = JasperFillManager.fillReport(jr,map, new utilites.MaConnexion().getInstance());  
                            // JasperViewer jv = new JasperViewer(jp);  
                            JRViewer jrv=new JRViewer(jp);
                            jScrollPane1.setViewportView(jrv);
                            jScrollPane1.repaint();
                            JBPdf.setEnabled(false);

                        }catch(Exception e){
                              JOptionPane.showMessageDialog(this, ""+e.getMessage());
                        }
    }//GEN-LAST:event_JBPdfActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBExcel;
    private javax.swing.JButton JBPdf;
    private javax.swing.JButton JBSupprimer;
    private javax.swing.JLabel JLabelDateDeb;
    private javax.swing.JLabel JLabelDateFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRepartionAuto;
    // End of variables declaration//GEN-END:variables
}
