/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entite.Activite;
import entite.Evaluation;
import entite.Fait;
import entite.Note;
import entite.Planning;
import entite.Site;
import java.util.List;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import utilites.Theme;

/**
 *
 * @author daniel
 */
public class JP_Rapport extends javax.swing.JPanel {
    private accesData.AccesData ad;
    private String nomProclamateur,date,HeureDeb,HeureFin;
    private List<Planning> listPlanning;
    private List<Site> listSite;
    private List<Note> listNote;
    private Vector vecIDPlanning,vecDate;
    private Vector<Fait> vecF;
    private Planning p=null;
    private Site site;
    private Activite activite;
    private Evaluation evaluation;
    private Vector vecNote;
   
    /**
     * Creates new form JP_Rapport
     */
    public JP_Rapport(accesData.AccesData ad) {
        this.ad=ad;
        listPlanning=ad.getListe("Planning.findAllGroupe");
        listSite=ad.getListe("Site.findAll");
        listNote=ad.getListe("Note.findAll");
        vecNote=new Note().getLibelle(listNote);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPeriode = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxSite = new javax.swing.JComboBox(new Site().listSiteNom(listSite));
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableActivite = new javax.swing.JTable();
        JBAjouterActiv = new javax.swing.JButton();
        JBModifierActiv = new javax.swing.JButton();
        JBSupprimerActiv = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEvaluation = new javax.swing.JTable();
        JBSupprimerEval = new javax.swing.JButton();
        JBModifierEval = new javax.swing.JButton();
        JBAjouterEval = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTFDateFait = new javax.swing.JTextField();
        JTFTrancheH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneCom = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableFait = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonExcellent = new javax.swing.JRadioButton();
        jRadioButtonBon = new javax.swing.JRadioButton();
        jRadioButtonPassable = new javax.swing.JRadioButton();
        JBAjouterFait = new javax.swing.JButton();
        JBModifierFait = new javax.swing.JButton();
        JBSupprimerFait = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rapports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(51, 51, 255)));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Période");

        jComboBoxPeriode.setEnabled(false);
        jComboBoxPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPeriodeActionPerformed(evt);
            }
        });

        jLabel7.setText("Site");

        jComboBoxSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxSite, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(810, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBoxPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jComboBoxSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Rubriques"));

        jTableActivite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Tranche Horaire", "Livre", "Tract", "Brochure", "Périodique", "S 43"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableActivite);

        JBAjouterActiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouter.png"))); // NOI18N
        JBAjouterActiv.setText("Ajouter");
        JBAjouterActiv.setEnabled(false);
        JBAjouterActiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterActivActionPerformed(evt);
            }
        });

        JBModifierActiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modifier.gif"))); // NOI18N
        JBModifierActiv.setText("Modifier");
        JBModifierActiv.setEnabled(false);
        JBModifierActiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModifierActivActionPerformed(evt);
            }
        });

        JBSupprimerActiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer.png"))); // NOI18N
        JBSupprimerActiv.setText("Supprimer");
        JBSupprimerActiv.setEnabled(false);
        JBSupprimerActiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSupprimerActivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JBAjouterActiv)
                        .addGap(18, 18, 18)
                        .addComponent(JBModifierActiv)
                        .addGap(18, 18, 18)
                        .addComponent(JBSupprimerActiv)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAjouterActiv)
                    .addComponent(JBModifierActiv)
                    .addComponent(JBSupprimerActiv))
                .addContainerGap(870, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Activité journalière", jPanel3);

        jTableEvaluation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nom du proclamateur", "Date", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableEvaluation);

        JBSupprimerEval.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer.png"))); // NOI18N
        JBSupprimerEval.setText("Supprimer");
        JBSupprimerEval.setEnabled(false);
        JBSupprimerEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSupprimerEvalActionPerformed(evt);
            }
        });

        JBModifierEval.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modifier.gif"))); // NOI18N
        JBModifierEval.setText("Modifier");
        JBModifierEval.setEnabled(false);
        JBModifierEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModifierEvalActionPerformed(evt);
            }
        });

        JBAjouterEval.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouter.png"))); // NOI18N
        JBAjouterEval.setText("Ajouter");
        JBAjouterEval.setEnabled(false);
        JBAjouterEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterEvalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(JBAjouterEval)
                .addGap(18, 18, 18)
                .addComponent(JBModifierEval)
                .addGap(18, 18, 18)
                .addComponent(JBSupprimerEval)
                .addContainerGap(375, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAjouterEval)
                    .addComponent(JBModifierEval)
                    .addComponent(JBSupprimerEval))
                .addContainerGap(869, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Evaluation du proclamateur", jPanel4);

        jLabel3.setText("Date");

        jLabel4.setText("Tranche horaire");

        jLabel5.setText("Commentaire");

        JTFDateFait.setEditable(false);

        JTFTrancheH.setEditable(false);

        jScrollPane1.setViewportView(jEditorPaneCom);

        jTableFait.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Note", "Commentaire"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFait.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFaitMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableFait);

        jLabel6.setText("Note");

        buttonGroup1.add(jRadioButtonExcellent);
        jRadioButtonExcellent.setText("Excellent");

        buttonGroup1.add(jRadioButtonBon);
        jRadioButtonBon.setText("Bon");
        jRadioButtonBon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBonActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPassable);
        jRadioButtonPassable.setText("Passable");

        JBAjouterFait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouter.png"))); // NOI18N
        JBAjouterFait.setText("Ajouter");
        JBAjouterFait.setEnabled(false);
        JBAjouterFait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterFaitActionPerformed(evt);
            }
        });

        JBModifierFait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modifier.gif"))); // NOI18N
        JBModifierFait.setText("Modifier");
        JBModifierFait.setEnabled(false);
        JBModifierFait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModifierFaitActionPerformed(evt);
            }
        });

        JBSupprimerFait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer.png"))); // NOI18N
        JBSupprimerFait.setText("Supprimer");
        JBSupprimerFait.setEnabled(false);
        JBSupprimerFait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSupprimerFaitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(JTFTrancheH, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                        .addComponent(JTFDateFait)))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(65, 65, 65)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jRadioButtonExcellent)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonBon)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonPassable))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(JBAjouterFait)
                        .addGap(18, 18, 18)
                        .addComponent(JBModifierFait)
                        .addGap(18, 18, 18)
                        .addComponent(JBSupprimerFait)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFDateFait, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFTrancheH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonExcellent)
                        .addComponent(jRadioButtonBon)
                        .addComponent(jRadioButtonPassable)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAjouterFait)
                    .addComponent(JBModifierFait)
                    .addComponent(JBSupprimerFait))
                .addContainerGap(557, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fait de prédication", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Activité journalière");

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel2.setText("                                          ");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Planning");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Jour1");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("t1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("t2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("t3");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Jour2");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("t1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("t2r");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("t3");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Jour3");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("t1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("t2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("t3i");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel6, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void JBModifierActivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModifierActivActionPerformed
        // TODO add your handling code here:
        int liv=0,tr=0,br=0,per=0,s4=0;
        activite=ad.getEm().find(Activite.class, activite.getIdactivite());
        try{
            liv=Integer.parseInt(jTableActivite.getValueAt(0, 2).toString());
            tr=Integer.parseInt(jTableActivite.getValueAt(0, 3).toString());
            br=Integer.parseInt(jTableActivite.getValueAt(0, 4).toString());
            per=Integer.parseInt(jTableActivite.getValueAt(0, 5).toString());
            s4=Integer.parseInt(jTableActivite.getValueAt(0, 6).toString());
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Vous devez fournir des valeures enti\u00E8res", "Erreure de saisie",JOptionPane.ERROR_MESSAGE);
        }
        activite.setLivre(liv);activite.setTract(tr);activite.setBrochure(br);activite.setPeriodique(per);activite.setS43(s4);
        ad.getTransac().begin();
        ad.getEm().flush();
        ad.getTransac().commit();
       
    }//GEN-LAST:event_JBModifierActivActionPerformed

    private void JBModifierEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModifierEvalActionPerformed
        // TODO add your handling code here:
        if(evaluation==null){
            JOptionPane.showMessageDialog(this, "Selectionner d'abord le nom d'un proclamateur","Information incompl\u00E8te",JOptionPane.ERROR_MESSAGE);
            return;
        }
        Evaluation e=ad.getEm().find(Evaluation.class, evaluation.getIdevaluation());
        e.setIdnote(new Note().getNote(listNote,jTableEvaluation.getValueAt(0, 2).toString()));
        e.setIdplanning(p);
        
        ad.getTransac().begin();
        ad.getEm().flush();
        ad.getTransac().commit();
            
    }//GEN-LAST:event_JBModifierEvalActionPerformed

    private void jComboBoxPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPeriodeActionPerformed
        // TODO add your handling code here:
        if(jComboBoxPeriode.getItemCount()>0){
           StringTokenizer st=new StringTokenizer(jComboBoxPeriode.getSelectedItem().toString()," Au ");
           String dateDeb=new utilites.date.FDate().formatDateFrom_FR_to_SQL(st.nextToken(), "-");
           String dateFin=new utilites.date.FDate().formatDateFrom_FR_to_SQL(st.nextToken(), "-");

           new utilites.Utilitaire().chargeArbreResurs(jScrollPane4,jTree1,"Planning",new Theme(), dateDeb, dateFin);
 
        }
        
    }//GEN-LAST:event_jComboBoxPeriodeActionPerformed

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTree1MouseClicked

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode node=(DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();
        if(node.isLeaf()){
            nomProclamateur=new utilites.Utilitaire().extraiNomProc(node.getUserObject().toString());
            DefaultMutableTreeNode node1=(DefaultMutableTreeNode)node.getParent();
            HeureDeb=new utilites.Utilitaire().extraiHeureDeb(node1.getUserObject().toString());
            HeureFin=new utilites.Utilitaire().extraiHeureFin(node1.getUserObject().toString());
            DefaultMutableTreeNode node2=(DefaultMutableTreeNode)node1.getParent();
            date=new utilites.Utilitaire().extraitDate(node2.getUserObject().toString());
            //chargement de la table evaluation
            // jTableEvaluation.setValueAt(nomProclamateur,0, 0); jTableEvaluation.setValueAt(date,0,1);
            Vector GV=new Vector(); Vector V=new Vector();
            V.addElement(nomProclamateur);V.addElement(date);V.addElement("");
            GV.addElement(V);
            new utilites.table.combo.GestionTable_Combo().chargeTable(jTableEvaluation, GV,new String[] { "Nom du proclamateur", "Date","Note"},new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class},2,vecNote);
            //recherche de l'avaluation du proclamateur courant
            p=ad.getEm().find(Planning.class,new Planning().getPlanningID(site, ad, date, HeureDeb, HeureFin, nomProclamateur));
            evaluation=new Evaluation().getEvaluation(p, ad);
            if(evaluation!=null){
                jTableEvaluation.setValueAt(evaluation.getIdnote().getLibelle(), 0, 2);
                JBAjouterEval.setEnabled(true);JBModifierEval.setEnabled(true);JBSupprimerEval.setEnabled(true);
            }else{
                jTableEvaluation.setValueAt("", 0, 2);
                JBAjouterEval.setEnabled(true);JBModifierEval.setEnabled(false);JBSupprimerEval.setEnabled(false);
            }
            
        }else{
            DefaultMutableTreeNode node1=(DefaultMutableTreeNode)node.getParent();
            if(!node1.isRoot()){
                HeureDeb=new utilites.Utilitaire().extraiHeureDeb(node.getUserObject().toString());
                HeureFin=new utilites.Utilitaire().extraiHeureFin(node.getUserObject().toString());
                
                date=new utilites.Utilitaire().extraitDate(node1.getUserObject().toString());
                
                //Initialisation du vecteur des plannings
                vecIDPlanning=new Planning().getPlanningID(site, ad, date, HeureDeb, HeureFin);
                
                //chargement de la table activite
                jTableActivite.setValueAt(date,0, 0); jTableActivite.setValueAt(HeureDeb+"-"+HeureFin,0,1);
                activite=ad.getEm().find(Activite.class,new Activite().getIdActivite(vecIDPlanning));
                if(activite!=null){
                    jTableActivite.setValueAt(activite.getLivre(),0,2);jTableActivite.setValueAt(activite.getTract(),0,3);
                    jTableActivite.setValueAt(activite.getBrochure(),0,4);jTableActivite.setValueAt(activite.getPeriodique(),0,5);
                    jTableActivite.setValueAt(activite.getS43(),0,6);
                    JBAjouterActiv.setEnabled(true);JBSupprimerActiv.setEnabled(true);JBModifierActiv.setEnabled(true);
                
                }else{
                     jTableActivite.setValueAt("",0,2);jTableActivite.setValueAt("",0,3);
                     jTableActivite.setValueAt("",0,4);jTableActivite.setValueAt("",0,5);jTableActivite.setValueAt("",0,6);
                     JBAjouterActiv.setEnabled(true);JBSupprimerActiv.setEnabled(false);JBModifierActiv.setEnabled(false);
                
                }
                //chargement de la table d'evaluation du proclamateur
                
                
                //chargement de la table des faits de predication
                JTFDateFait.setText(date);JTFTrancheH.setText(HeureDeb+"-"+HeureFin);
                vecF=new Fait().getFaits(vecIDPlanning);
                if(vecF.size()>0){
                     new utilites.table.GestionTable().chargeTable(jTableFait, new Fait().dataFait(vecF),new String[] { "Note", "Commentaire"},new Class[] {java.lang.String.class, java.lang.String.class});
                     JBAjouterFait.setEnabled(true);JBModifierFait.setEnabled(true);JBSupprimerFait.setEnabled(true);
                }else{
                    JBAjouterFait.setEnabled(true);JBModifierFait.setEnabled(false);JBSupprimerFait.setEnabled(false);
                }
                
            }else{
                date=new utilites.Utilitaire().extraitDate(node.getUserObject().toString());
                 //chargement de la table activite
                jTableActivite.setValueAt(date,0, 0);jTableActivite.setValueAt("",0, 1);
            }
            
        }
        System.out.println(" date "+date+" heurD "+HeureDeb+" hueF "+HeureFin);
       
        
        
        

    }//GEN-LAST:event_jTree1ValueChanged

    private void JBAjouterActivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterActivActionPerformed
        // TODO add your handling code here:
        Activite a=new Activite();int liv=0,tr=0,br=0,per=0,s4=0;
        try{
            liv=Integer.parseInt(jTableActivite.getValueAt(0, 2).toString());
            tr=Integer.parseInt(jTableActivite.getValueAt(0, 3).toString());
            br=Integer.parseInt(jTableActivite.getValueAt(0, 4).toString());
            per=Integer.parseInt(jTableActivite.getValueAt(0, 5).toString());
            s4=Integer.parseInt(jTableActivite.getValueAt(0, 6).toString());
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Vous devez fournir des valeures enti\u00E8res", "Erreure de saisie",JOptionPane.ERROR_MESSAGE);
        }
        a.setLivre(liv);a.setTract(tr);a.setBrochure(br);a.setPeriodique(per);a.setS43(s4);
        a.insertActivite(vecIDPlanning);
        
        
    }//GEN-LAST:event_JBAjouterActivActionPerformed

    private void jRadioButtonBonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBonActionPerformed

    private void JBModifierFaitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModifierFaitActionPerformed
        // TODO add your handling code here:
       if(jTableFait.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Selectionnez d'abord un fait pr\u00E9dication","Information incompl\u00E8te",JOptionPane.ERROR_MESSAGE);
            return;
        }
        Fait f=ad.getEm().find(Fait.class,vecF.elementAt(jTableFait.getSelectedRow()).getIdfait());
        
        
        f.setContenu(jEditorPaneCom.getText());
        if(jRadioButtonBon.isSelected())
           f.setNote("Bon"); 
        else if(jRadioButtonExcellent.isSelected())
           f.setNote("Excellent"); 
        else if(jRadioButtonPassable.isSelected())
           f.setNote("Passable");
        
        ad.getTransac().begin();
        ad.getEm().flush();
        ad.getTransac().commit();
        
         vecF=new Fait().getFaits(vecIDPlanning);
                if(vecF.size()>0){
                     new utilites.table.GestionTable().chargeTable(jTableFait, new Fait().dataFait(vecF),new String[] { "Note", "Commentaire"},new Class[] {java.lang.String.class, java.lang.String.class});
        
                }
        
    }//GEN-LAST:event_JBModifierFaitActionPerformed

    private void jComboBoxSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSiteActionPerformed
        // TODO add your handling code here:
        site=listSite.get(jComboBoxSite.getSelectedIndex());
        
        vecIDPlanning=ad.requeteNative_Vector("select idplanning/*,concat_ws(' Au ',date_format(min(datej),'%d-%m-%Y'),date_format(max(datej),'%d-%m-%Y'))*/ from planning where idproclamateur in(select idproclamateur from proc_site where idsite="+site.getIdsite()+") group by groupe");
        vecDate=ad.requeteNative_Vector("select /*idplanning,*/concat_ws(' Au ',date_format(min(datej),'%d-%m-%Y'),date_format(max(datej),'%d-%m-%Y')) from planning where idproclamateur in(select idproclamateur from proc_site where idsite="+site.getIdsite()+") group by groupe");
        new utilites.Utilitaire().chargeCombo(jComboBoxPeriode, vecDate);
        jComboBoxPeriode.setEnabled(true);
    }//GEN-LAST:event_jComboBoxSiteActionPerformed

    private void JBAjouterFaitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterFaitActionPerformed
        // TODO add your handling code here:
        Fait f=new Fait();
        f.setContenu(jEditorPaneCom.getText());
        if(jRadioButtonBon.isSelected())
           f.setNote("Bon"); 
        else if(jRadioButtonExcellent.isSelected())
           f.setNote("Excellent"); 
        else if(jRadioButtonPassable.isSelected())
           f.setNote("Passable");
        else{
            JOptionPane.showMessageDialog(this,"Specifiez une note pour ce fait de pr\u00E9dication","Information incompl\u00E8te",JOptionPane.ERROR_MESSAGE);
            return;
        }
        f.insertFait(vecIDPlanning);
        
        vecF=new Fait().getFaits(vecIDPlanning);
                if(vecF.size()>0){
                     new utilites.table.GestionTable().chargeTable(jTableFait, new Fait().dataFait(vecF),new String[] { "Note", "Commentaire"},new Class[] {java.lang.String.class, java.lang.String.class});
        
                }
        
    }//GEN-LAST:event_JBAjouterFaitActionPerformed

    private void JBSupprimerFaitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSupprimerFaitActionPerformed
        // TODO add your handling code here:
        if(jTableFait.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Selectionnez d'abord un fait pr\u00E9dication","Information incompl\u00E8te",JOptionPane.ERROR_MESSAGE);
            return;
        }
        Fait f=ad.getEm().find(Fait.class,vecF.elementAt(jTableFait.getSelectedRow()).getIdfait());
        
        if(JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer ce fait?","Confirmer votre choix",JOptionPane.OK_CANCEL_OPTION)!=0)
            return;
        
        ad.getTransac().begin();
        ad.getEm().remove(f);
        ad.getTransac().commit();
        
         vecF=new Fait().getFaits(vecIDPlanning);
                if(vecF.size()>0){
                     new utilites.table.GestionTable().chargeTable(jTableFait, new Fait().dataFait(vecF),new String[] { "Note", "Commentaire"},new Class[] {java.lang.String.class, java.lang.String.class});
        
                }
       
    }//GEN-LAST:event_JBSupprimerFaitActionPerformed

    private void JBAjouterEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterEvalActionPerformed
        // TODO add your handling code here:
        Evaluation e=new Evaluation();
        e.setIdnote(new Note().getNote(listNote,jTableEvaluation.getValueAt(0, 2).toString()));
        e.setIdplanning(p);
        
        ad.getTransac().begin();
        ad.getEm().persist(e);
        ad.getTransac().commit();
        
    }//GEN-LAST:event_JBAjouterEvalActionPerformed

    private void JBSupprimerEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSupprimerEvalActionPerformed
        // TODO add your handling code here:
         if(evaluation==null){
            JOptionPane.showMessageDialog(this, "Selectionner d'abord le nom d'un proclamateur","Information incompl\u00E8te",JOptionPane.ERROR_MESSAGE);
            return;
        }
        Evaluation e=ad.getEm().find(Evaluation.class, evaluation.getIdevaluation());
        if(JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer cette note?","Confirmer votre choix",JOptionPane.OK_CANCEL_OPTION)!=0)
            return;
        
        ad.getTransac().begin();
        ad.getEm().remove(e);
        ad.getTransac().commit();
        
        jTableEvaluation.setValueAt("",0, 2);
       
    }//GEN-LAST:event_JBSupprimerEvalActionPerformed

    private void JBSupprimerActivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSupprimerActivActionPerformed
        // TODO add your handling code here:
        activite=ad.getEm().find(Activite.class, activite.getIdactivite());
        if(JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer ces valeurs?","Confirmer votre choix",JOptionPane.OK_CANCEL_OPTION)!=0)
            return;
        
        ad.getTransac().begin();
        ad.getEm().remove(activite);
        ad.getTransac().commit();
        
        jTableActivite.setValueAt("",0,2);jTableActivite.setValueAt("",0,3);
        jTableActivite.setValueAt("",0,4);jTableActivite.setValueAt("",0,5);jTableActivite.setValueAt("",0,6);
    }//GEN-LAST:event_JBSupprimerActivActionPerformed

    private void jTableFaitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFaitMouseClicked
        // TODO add your handling code here:
        Fait f=ad.getEm().find(Fait.class,vecF.elementAt(jTableFait.getSelectedRow()).getIdfait());
        if(f.getNote().equalsIgnoreCase("Bon"))
            jRadioButtonBon.setSelected(true);
        else if(f.getNote().equalsIgnoreCase("Excellent"))
            jRadioButtonExcellent.setSelected(true);
        else 
            jRadioButtonPassable.setSelected(true);
        jEditorPaneCom.setText(f.getContenu());
    }//GEN-LAST:event_jTableFaitMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAjouterActiv;
    private javax.swing.JButton JBAjouterEval;
    private javax.swing.JButton JBAjouterFait;
    private javax.swing.JButton JBModifierActiv;
    private javax.swing.JButton JBModifierEval;
    private javax.swing.JButton JBModifierFait;
    private javax.swing.JButton JBSupprimerActiv;
    private javax.swing.JButton JBSupprimerEval;
    private javax.swing.JButton JBSupprimerFait;
    private javax.swing.JTextField JTFDateFait;
    private javax.swing.JTextField JTFTrancheH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jComboBoxPeriode;
    private javax.swing.JComboBox jComboBoxSite;
    private javax.swing.JEditorPane jEditorPaneCom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButtonBon;
    private javax.swing.JRadioButton jRadioButtonExcellent;
    private javax.swing.JRadioButton jRadioButtonPassable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableActivite;
    private javax.swing.JTable jTableEvaluation;
    private javax.swing.JTable jTableFait;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
